version: '3'

services:
  bismillah-app:
    container_name: bismillah-app
    build:
      context: .
      dockerfile: DockerFile
    restart: always
    ports:
      - 3310:3310
    networks:
      - my_network
    environment:
      - NEXT_PUBLIC_API_URL
  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
